--
-- PostgreSQL database dump
--

-- restrict 9FJgtDZiFNFd8hFfsB7yoxmmKprisziTOmVJZ5Esc2xxPP3cw1i8x8jbgZkv1lb

-- Dumped from database version 18.3 (Debian 18.3-1.pgdg13+1)
-- Dumped by pg_dump version 18.3 (Debian 18.3-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


--
-- Name: LogEntries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."LogEntries" (
    "Id" integer NOT NULL,
    "VehicleId" integer NOT NULL,
    "DateTime" timestamp without time zone NOT NULL,
    "OdometerKm" numeric(10,2) NOT NULL,
    "FuelLoaded" boolean NOT NULL,
    "FuelLiters" numeric(8,3),
    "FuelPricePerLiter" numeric(8,3),
    "FuelTotalPaid" numeric(10,2),
    "PetrolStationName" text
);


--
-- Name: LogEntries_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."LogEntries" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LogEntries_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ServiceDocuments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ServiceDocuments" (
    "Id" integer NOT NULL,
    "ServiceLogId" integer NOT NULL,
    "FileName" text NOT NULL,
    "FileUrl" text NOT NULL,
    "FileType" text NOT NULL,
    "UploadedAt" timestamp without time zone NOT NULL
);


--
-- Name: ServiceDocuments_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ServiceDocuments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ServiceDocuments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ServiceItems; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ServiceItems" (
    "Id" integer NOT NULL,
    "VehicleId" integer NOT NULL,
    "Name" text NOT NULL,
    "LastServiceDate" timestamp without time zone,
    "LastServiceKm" numeric(10,2),
    "IntervalKm" integer,
    "IntervalMonths" integer,
    "Notes" text
);


--
-- Name: ServiceItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ServiceItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ServiceItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ServiceLogItems; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ServiceLogItems" (
    "Id" integer NOT NULL,
    "ServiceLogId" integer NOT NULL,
    "ServiceItemId" integer NOT NULL,
    "Done" boolean NOT NULL
);


--
-- Name: ServiceLogItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ServiceLogItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ServiceLogItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ServiceLogs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ServiceLogs" (
    "Id" integer NOT NULL,
    "VehicleId" integer NOT NULL,
    "ServiceDate" timestamp without time zone NOT NULL,
    "OdometerKm" numeric(10,2) NOT NULL,
    "Notes" text
);


--
-- Name: ServiceLogs_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ServiceLogs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ServiceLogs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Vehicles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Vehicles" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "Name" text NOT NULL,
    "Make" text NOT NULL,
    "Model" text NOT NULL,
    "Year" integer NOT NULL,
    "LicensePlate" text NOT NULL
);


--
-- Name: Vehicles_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Vehicles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Vehicles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AspNetRoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;



--
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;



--
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AspNetUserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;



--
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AspNetUserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;



--
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AspNetUserRoles" ("UserId", "RoleId") FROM stdin;



--
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AspNetUserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;



--
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AspNetUsers" ("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
2fa23e02-edc7-4e66-af0d-59a1407cb57d	marcoslaranz@gmail.com	MARCOSLARANZ@GMAIL.COM	marcoslaranz@gmail.com	MARCOSLARANZ@GMAIL.COM	f	AQAAAAIAAYagAAAAEEqyxv33PC492eY1jg7y7rFnPY0R87BZfs89pBjFJUryw1ZqksXIrsrAfr+KkuPTQQ==	ZPP257A4IIIANUIYICTNFP6TS2GSZNS6	071ca357-6463-4b6e-ba4c-ea43e1760b33	\N	f	f	\N	t	0
1b3f1677-b336-4fd8-9d91-5a674be36cdf	marcoslaranz2@gmail.com	MARCOSLARANZ2@GMAIL.COM	marcoslaranz2@gmail.com	MARCOSLARANZ2@GMAIL.COM	f	AQAAAAIAAYagAAAAED8Yjl5ATxXKtPlAs84ymUY9tmXPgkdocURte+evKIz52V71Nfad+nf/7HeMX5rYMA==	57DBA3KXHUCADIDCOYRVRDTZPPFFOLYB	0abda40d-1724-4976-a7e2-d875a00f9575	\N	f	f	\N	t	0



--
-- Data for Name: LogEntries; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."LogEntries" ("Id", "VehicleId", "DateTime", "OdometerKm", "FuelLoaded", "FuelLiters", "FuelPricePerLiter", "FuelTotalPaid", "PetrolStationName") FROM stdin;
11	1	2026-04-13 20:27:00	181117.00	t	13.750	\N	50.10	Z Warkworth
12	1	2026-04-13 07:00:00	180823.00	f	\N	\N	\N	\N
13	1	2026-04-14 07:00:00	181117.00	f	\N	\N	\N	\N
14	1	2026-04-14 20:39:00	181404.00	t	15.340	\N	54.90	Gull - Avondale
15	1	2026-04-15 07:00:00	181407.00	f	\N	\N	\N	\N
16	1	2026-04-15 20:47:00	181680.00	t	11.450	\N	41.48	\N
17	1	2026-04-16 07:00:00	181680.00	f	\N	\N	\N	\N
18	1	2026-04-16 20:51:00	182037.00	t	12.690	\N	45.85	\N
19	1	2026-04-17 08:02:00	182037.00	f	\N	\N	\N	\N
23	1	2026-04-19 11:17:00	182417.00	f	\N	\N	\N	\N
25	1	2026-04-20 06:41:00	182605.00	t	24.310	3.449	83.85	Gull Avondale
20	1	2026-04-17 20:53:00	182347.00	t	14.110	\N	44.94	Z Warkworth
26	1	2026-04-21 19:46:00	182802.00	t	9.660	3.598	33.95	Z Warkworth 
27	1	2026-04-20 19:06:00	182799.00	f	\N	\N	\N	\N
28	1	2026-04-21 08:21:23.904	183081.00	f	\N	\N	\N	\N
29	1	2026-04-22 07:20:00	183084.00	t	12.430	3.560	43.36	Z Warkworth 
30	1	2026-04-22 07:35:14.26	183328.00	f	\N	\N	\N	\N
31	1	2026-04-23 07:20:00	183330.00	t	11.200	3.549	38.87	Z Warkworth
32	1	2026-04-23 08:06:05.406	183672.00	f	\N	\N	\N	\N
33	1	2026-04-24 07:08:00	183675.00	t	14.340	3.540	49.77	Z Warkworth
34	1	2026-04-24 07:52:50.317	183957.00	f	\N	\N	\N	\N
35	1	2026-04-28 06:59:00	184023.00	t	16.210	3.429	55.58	\N
36	1	2026-04-28 08:13:53.189	184261.00	f	\N	\N	\N	\N
37	1	2026-04-29 07:13:00	184264.00	t	11.700	3.509	39.06	Z Wadsworth 
39	1	2026-04-30 07:15:00	184535.00	t	12.180	3.479	41.41	\N
40	1	2026-04-29 19:44:00	184533.00	f	\N	\N	\N	\N
41	1	2026-04-30 19:09:00	184813.00	f	\N	\N	\N	\N
42	1	2026-05-01 07:11:00	184816.00	t	13.150	3.479	44.71	Z Warkworth 
43	1	2026-05-01 07:13:49.932	185118.00	f	\N	\N	\N	\N
45	1	2026-05-04 07:58:53	185121.00	t	1.420	3.460	45.51	Z Warkworth 
46	1	2026-05-04 19:01:42	185360.00	f	\N	\N	\N	\N
47	1	2026-05-05 06:55:55	185426.00	t	13.330	3.479	45.38	Gull Avondale 
48	1	2026-05-05 19:34:11	185726.00	f	\N	\N	\N	\N
49	1	2026-05-06 10:12:25	185728.00	t	14.180	3.549	48.92	Z Workworth
50	1	2026-05-07 08:17:36	186044.00	t	13.800	3.549	47.94	Z Warkworth 
51	1	2026-05-07 20:49:55	186398.00	f	\N	\N	\N	\N
52	1	2026-05-08 08:06:52	186398.00	t	15.950	3.485	54.59	Z Warkworth 
53	1	2026-05-08 21:01:49	186706.00	f	\N	\N	\N	\N
54	1	2026-05-11 08:02:16	186713.00	t	14.950	3.489	51.04	Z Warkworth
55	1	2026-05-11 19:50:34	187004.00	f	\N	\N	\N	\N
56	1	2026-05-12 07:04:45	187070.00	t	16.110	3.439	55.40	Gull Avondale
57	1	2026-05-12 19:52:14	187331.00	f	\N	\N	\N	\N
58	1	2026-05-13 08:28:57	187335.00	t	11.810	3.479	39.99	Z Warkworth
59	1	2026-05-13 20:04:36	187614.00	f	\N	\N	\N	\N
60	1	2026-05-14 07:55:41	187617.00	t	13.200	3.469	44.75	Z Warkworth
61	1	2026-05-14 20:28:14	187894.00	f	\N	\N	\N	\N
\.


--
-- Data for Name: ServiceDocuments; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."ServiceDocuments" ("Id", "ServiceLogId", "FileName", "FileUrl", "FileType", "UploadedAt") FROM stdin;
\.


--
-- Data for Name: ServiceItems; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."ServiceItems" ("Id", "VehicleId", "Name", "LastServiceDate", "LastServiceKm", "IntervalKm", "IntervalMonths", "Notes") FROM stdin;
11	1	Chassis Lubrication	2026-03-16 00:00:00	175076.00	10000	12	\N
12	1	Windshield Washer Fluid	2026-03-16 00:00:00	175076.00	5000	6	\N
14	1	Power Steering Fluid	2026-03-16 00:00:00	175076.00	10000	12	\N
15	1	Transmission Fluid	2026-03-16 00:00:00	175076.00	10000	12	\N
16	1	Rear Differential Fluid	2026-03-16 00:00:00	175076.00	10000	12	\N
17	1	Front Differential Fluid	2026-03-16 00:00:00	175076.00	10000	12	\N
18	1	Transfer Case Fluid	2026-03-16 00:00:00	175076.00	10000	12	\N
20	1	Check Exhaust System	2026-03-16 00:00:00	175076.00	10000	12	\N
21	1	Check Shocks and Struts	2026-03-16 00:00:00	175076.00	10000	12	\N
22	1	Check C.V. Boots	2026-03-16 00:00:00	175076.00	10000	12	\N
23	1	Sump Plug Washer	2026-03-16 00:00:00	175076.00	10000	12	\N
9	1	Change Oil	2025-11-25 00:00:00	159850.00	10000	12	\N
10	1	Replace Oil Filter	2025-11-25 00:00:00	159850.00	10000	12	\N
13	1	Brake Fluid	2026-05-12 00:00:00	186988.00	10000	12	\N
19	1	Air Filter	2026-05-12 00:00:00	186842.00	10000	12	\N
\.


--
-- Data for Name: ServiceLogItems; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."ServiceLogItems" ("Id", "ServiceLogId", "ServiceItemId", "Done") FROM stdin;
1	1	19	t
2	1	13	t
3	1	9	t
4	1	11	t
5	1	22	t
6	1	20	t
7	1	21	t
8	1	17	t
9	1	14	t
10	1	16	t
11	1	10	t
12	1	23	t
13	1	18	t
14	1	15	t
15	1	12	t
16	2	19	f
17	2	13	f
18	2	9	t
19	2	11	f
20	2	22	f
21	2	20	f
22	2	21	f
23	2	17	f
24	2	14	f
25	2	16	f
26	2	10	t
27	2	23	f
28	2	18	f
29	2	15	f
30	2	12	f
31	3	19	t
32	3	13	t
33	3	9	f
34	3	11	f
35	3	22	f
36	3	20	f
37	3	21	f
38	3	17	f
39	3	14	f
40	3	16	f
41	3	10	f
42	3	23	f
43	3	18	f
44	3	15	f
45	3	12	f
46	4	19	t
47	4	13	t
48	4	9	f
49	4	11	f
50	4	22	f
51	4	20	f
52	4	21	f
53	4	17	f
54	4	14	f
55	4	16	f
56	4	10	f
57	4	23	f
58	4	18	f
59	4	15	f
60	4	12	f
61	5	19	t
62	5	13	f
63	5	9	f
64	5	11	f
65	5	22	f
66	5	20	f
67	5	21	f
68	5	17	f
69	5	14	f
70	5	16	f
71	5	10	f
72	5	23	f
73	5	18	f
74	5	15	f
75	5	12	f
\.


--
-- Data for Name: ServiceLogs; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."ServiceLogs" ("Id", "VehicleId", "ServiceDate", "OdometerKm", "Notes") FROM stdin;
1	1	2026-03-16 00:00:00	175076.00	Oil Changers
2	1	2025-11-25 00:00:00	159850.00	Albany Toyota
3	1	2026-05-12 00:00:00	186988.00	Test
4	1	2026-05-12 00:00:00	186988.00	Test
5	1	2026-05-12 00:00:00	186842.00	test2
\.


--
-- Data for Name: Vehicles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Vehicles" ("Id", "UserId", "Name", "Make", "Model", "Year", "LicensePlate") FROM stdin;
1	2fa23e02-edc7-4e66-af0d-59a1407cb57d	Prious	Toyota	Prious	2020	RLR364
2	2fa23e02-edc7-4e66-af0d-59a1407cb57d	Freeland	LandRover	FreeLand2	2011	GAR663
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260412061909_InitialCreate	10.0.5
20260418091254_UpdateModel	10.0.5
20260509062521_AddServiceItems	10.0.5
20260509083357_AddServiceLogsAndDocuments	10.0.5
\.


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- Name: LogEntries_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."LogEntries_Id_seq"', 61, true);


--
-- Name: ServiceDocuments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."ServiceDocuments_Id_seq"', 1, false);


--
-- Name: ServiceItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."ServiceItems_Id_seq"', 23, true);


--
-- Name: ServiceLogItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."ServiceLogItems_Id_seq"', 75, true);


--
-- Name: ServiceLogs_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."ServiceLogs_Id_seq"', 5, true);


--
-- Name: Vehicles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Vehicles_Id_seq"', 2, true);


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: LogEntries PK_LogEntries; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."LogEntries"
    ADD CONSTRAINT "PK_LogEntries" PRIMARY KEY ("Id");


--
-- Name: ServiceDocuments PK_ServiceDocuments; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ServiceDocuments"
    ADD CONSTRAINT "PK_ServiceDocuments" PRIMARY KEY ("Id");


--
-- Name: ServiceItems PK_ServiceItems; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ServiceItems"
    ADD CONSTRAINT "PK_ServiceItems" PRIMARY KEY ("Id");


--
-- Name: ServiceLogItems PK_ServiceLogItems; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ServiceLogItems"
    ADD CONSTRAINT "PK_ServiceLogItems" PRIMARY KEY ("Id");


--
-- Name: ServiceLogs PK_ServiceLogs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ServiceLogs"
    ADD CONSTRAINT "PK_ServiceLogs" PRIMARY KEY ("Id");


--
-- Name: Vehicles PK_Vehicles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Vehicles"
    ADD CONSTRAINT "PK_Vehicles" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_LogEntries_VehicleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_LogEntries_VehicleId" ON public."LogEntries" USING btree ("VehicleId");


--
-- Name: IX_ServiceDocuments_ServiceLogId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ServiceDocuments_ServiceLogId" ON public."ServiceDocuments" USING btree ("ServiceLogId");


--
-- Name: IX_ServiceItems_VehicleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ServiceItems_VehicleId" ON public."ServiceItems" USING btree ("VehicleId");


--
-- Name: IX_ServiceLogItems_ServiceItemId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ServiceLogItems_ServiceItemId" ON public."ServiceLogItems" USING btree ("ServiceItemId");


--
-- Name: IX_ServiceLogItems_ServiceLogId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ServiceLogItems_ServiceLogId" ON public."ServiceLogItems" USING btree ("ServiceLogId");


--
-- Name: IX_ServiceLogs_VehicleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ServiceLogs_VehicleId" ON public."ServiceLogs" USING btree ("VehicleId");


--
-- Name: IX_Vehicles_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Vehicles_UserId" ON public."Vehicles" USING btree ("UserId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: LogEntries FK_LogEntries_Vehicles_VehicleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."LogEntries"
    ADD CONSTRAINT "FK_LogEntries_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES public."Vehicles"("Id") ON DELETE CASCADE;


--
-- Name: ServiceDocuments FK_ServiceDocuments_ServiceLogs_ServiceLogId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ServiceDocuments"
    ADD CONSTRAINT "FK_ServiceDocuments_ServiceLogs_ServiceLogId" FOREIGN KEY ("ServiceLogId") REFERENCES public."ServiceLogs"("Id") ON DELETE CASCADE;


--
-- Name: ServiceItems FK_ServiceItems_Vehicles_VehicleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ServiceItems"
    ADD CONSTRAINT "FK_ServiceItems_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES public."Vehicles"("Id") ON DELETE CASCADE;


--
-- Name: ServiceLogItems FK_ServiceLogItems_ServiceItems_ServiceItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ServiceLogItems"
    ADD CONSTRAINT "FK_ServiceLogItems_ServiceItems_ServiceItemId" FOREIGN KEY ("ServiceItemId") REFERENCES public."ServiceItems"("Id") ON DELETE CASCADE;


--
-- Name: ServiceLogItems FK_ServiceLogItems_ServiceLogs_ServiceLogId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ServiceLogItems"
    ADD CONSTRAINT "FK_ServiceLogItems_ServiceLogs_ServiceLogId" FOREIGN KEY ("ServiceLogId") REFERENCES public."ServiceLogs"("Id") ON DELETE CASCADE;


--
-- Name: ServiceLogs FK_ServiceLogs_Vehicles_VehicleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ServiceLogs"
    ADD CONSTRAINT "FK_ServiceLogs_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES public."Vehicles"("Id") ON DELETE CASCADE;


--
-- Name: Vehicles FK_Vehicles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Vehicles"
    ADD CONSTRAINT "FK_Vehicles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 9FJgtDZiFNFd8hFfsB7yoxmmKprisziTOmVJZ5Esc2xxPP3cw1i8x8jbgZkv1lb

